version: '3.8'

services:
  sms_backuper:
    env_file:
      - .env
    build:
      context: .
    volumes:
      - $PWD:/app
    networks:
      - sms_backuper_network
    command:
      - 'tail'
      - '-f'
      - '/dev/null'

  mysql:
    env_file:
      - .env
    image: 'mysql:8'
    volumes:
      - sms_backuper_db
    networks:
      - sms_backuper_network

networks:
  sms_backuper_network:
    driver: bridge
volumes:
  sms_backuper_db:
    driver: local