version: '3.8'

services:
  backuper:
    env_file:
      - .env
    image: "sms-backup-service:latest"
    volumes:
      - $PWD:/srv/sms-backup-service
    networks:
      - sms_backuper_network
    command:
      - 'tail'
      - '-f'
      - '/dev/null'

  mysql:
    env_file:
      - .env
    image: 'mysql:8'
    volumes:
      - sms_backuper_db:/var/lib/mysql
    networks:
      - sms_backuper_network

networks:
  sms_backuper_network:
    driver: bridge
volumes:
  sms_backuper_db:
    driver: local
