version: '3.8'

services:
  sms_backuper:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
    image: "sms-backup-service:latest"
    volumes:
      - $PWD:/srv/sms-backup-service
    networks:
      - sms_backuper_network
    command:
      - 'tail'
      - '-f'
      - '/dev/null'

  mysql:
    restart: always
    env_file:
      - .env
    image: 'mysql:8'
    volumes:
      - sms_backuper_db:/var/lib/mysql
    networks:
      - sms_backuper_network
      
#  pma:
#    restart: unless-stopped
#    env_file:
#      - .env
#    image: 'phpmyadmin:5.2.0-apache'
#    networks:
#      - sms_backuper_network
#    ports:
#      - "8000:80"
#    environment:
#      - PMA_HOST=${MYSQL_HOST:-mysql}

networks:
  sms_backuper_network:
    driver: bridge
volumes:
  sms_backuper_db:
    driver: local
